# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yé Mistikrik ? - Association Théâtre de l'Efrei
lang: fr_FR
email: contact@ye-mistikrik.fr
description: >- # this means to ignore newlines until "baseurl:"
  Yé Mistikrik? est l'association Théâtre de l'Efrei. 
  Nous proposons aux étudiants divers évenements liés au théâtre et au stand-up.
author: "Yé Mistikrik?"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

google.analytics: UA-125319730-1

collections:
  - team

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag


defaults:
  -
    scope:
      path: ""
    values:
      layout: "home"


sass:
    style: compressed
    

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
